import type { RefEntry } from './reference';

/**
 * Thẻ tra cứu thêm từ bài "Phân tích kỹ thuật căn bản" chủ app gửi
 * (2026-10-07): nến đơn, cụm nến, mẫu giá còn thiếu, hai mức giá động, và
 * nhóm Chỉ báo mới.
 *
 * Ở `reference.ts`, mục nào có `patternId` thì hiện "App tự dò ở mục
 * Patterns". Ở đây chỉ ba thẻ thuộc họ doji mang `patternId: 'doji'`, vì máy
 * dò gọi MỌI nến thân ≤ 10% biên độ là doji — nó thấy được chúng, chỉ không
 * tách tên. Các thẻ còn lại app chưa tự dò và không được giả vờ là có.
 */
export const REFERENCE_MORE: RefEntry[] = [
  /* ---------------- nến đơn ---------------- */
  {
    id: 'marubozu', group: 'candle', figure: 'marubozu', side: 'bull',
    name: { vi: 'Marubozu tăng', en: 'Bullish marubozu' },
    gist: { vi: 'Thân xanh dài, gần như không râu: mở ở mức thấp nhất, đóng ở mức cao nhất. Phe mua giữ giá cả phiên.', en: 'A long green body with almost no wicks: opens at the low, closes at the high. Buyers held price all session.' },
    confirm: { vi: 'Là nến quyết tâm, không phải đảo chiều. Đáng chú ý nhất khi nó là nến phá vỡ một vùng kháng cự.', en: 'A conviction candle, not a reversal. Most telling when it is the candle that breaks a resistance zone.' },
    trap: { vi: 'Marubozu rất dài ngay sau tin có thể là cú chạy cạn sức; phiên sau hay lùi một phần.', en: 'A very long marubozu right after news can be exhaustion; the next session often gives some back.' },
    lesson: 'candles-more',
  },
  {
    id: 'bear-marubozu', group: 'candle', figure: 'bear-marubozu', side: 'bear',
    name: { vi: 'Marubozu giảm', en: 'Bearish marubozu' },
    gist: { vi: 'Thân đỏ dài không râu: mở ở mức cao nhất, đóng ở mức thấp nhất. Phe bán kiểm soát cả phiên.', en: 'A long red body with no wicks: opens at the high, closes at the low. Sellers controlled the whole session.' },
    confirm: { vi: 'Đáng chú ý nhất khi nó là nến thủng một vùng hỗ trợ.', en: 'Most telling when it is the candle that breaks a support zone.' },
    trap: { vi: 'Sau một đợt giảm đã rất dài, nó có thể là cú bán tháo cuối cùng chứ không phải khởi đầu.', en: 'After an already long decline it can be the final flush rather than a beginning.' },
    lesson: 'candles-more',
  },
  {
    id: 'spinning-top', group: 'candle', figure: 'spinning-top', side: 'neutral',
    name: { vi: 'Con xoay', en: 'Spinning top' },
    gist: { vi: 'Thân nhỏ, hai râu dài gần bằng nhau: giá chạy cả hai chiều rồi đóng gần chỗ mở.', en: 'A small body with two long, similar wicks: price ran both ways and closed near the open.' },
    confirm: { vi: 'Không tự xác nhận gì; nến sau quyết định hướng, giống doji.', en: 'Confirms nothing alone; the next candle decides, as with a doji.' },
    trap: { vi: 'Con xoay giữa vùng đi ngang chỉ là đi ngang.', en: 'A spinning top inside a range is just the range.' },
    lesson: 'candles-more',
  },
  {
    id: 'dragonfly-doji', group: 'candle', figure: 'dragonfly-doji', side: 'bull',
    name: { vi: 'Doji chuồn chuồn', en: 'Dragonfly doji' },
    gist: { vi: 'Mở, đóng và cao nhất gần bằng nhau, râu dưới rất dài. Phe bán đạp sâu rồi bị kéo về hết.', en: 'Open, close and high nearly equal, a very long lower wick. Sellers drove deep and were pulled all the way back.' },
    confirm: { vi: 'Sau đợt giảm, nến sau đóng CAO HƠN đỉnh của doji.', en: 'After a decline, the next candle closes ABOVE the doji’s high.' },
    trap: { vi: 'Mục Patterns gọi chung mọi kiểu này là "doji" — nó thấy, nhưng không tách tên.', en: 'Patterns calls all of these "doji" — it sees them, but does not name the variant.' },
    lesson: 'candles-more', patternId: 'doji',
  },
  {
    id: 'gravestone-doji', group: 'candle', figure: 'gravestone-doji', side: 'bear',
    name: { vi: 'Doji bia mộ', en: 'Gravestone doji' },
    gist: { vi: 'Mở, đóng và thấp nhất gần bằng nhau, râu trên rất dài. Phe mua đẩy cao rồi mất hết.', en: 'Open, close and low nearly equal, a very long upper wick. Buyers pushed high and lost it all.' },
    confirm: { vi: 'Sau đợt tăng, nến sau đóng THẤP HƠN đáy của doji.', en: 'After a rise, the next candle closes BELOW the doji’s low.' },
    trap: { vi: 'Ở giữa xu hướng giảm nó không nói thêm gì; vị trí ở đỉnh mới cho nó nghĩa.', en: 'Mid-downtrend it adds nothing; only a location at a top gives it meaning.' },
    lesson: 'candles-more', patternId: 'doji',
  },
  {
    id: 'long-legged-doji', group: 'candle', figure: 'long-legged-doji', side: 'neutral',
    name: { vi: 'Doji chân dài', en: 'Long-legged doji' },
    gist: { vi: 'Cả hai râu rất dài, đóng gần giá mở: biến động lớn mà không ai thắng.', en: 'Both wicks very long, closing near the open: a wide range and no winner.' },
    confirm: { vi: 'Nến sau đóng ra ngoài biên độ của doji — phía nào thì theo phía đó.', en: 'The next candle closes outside the doji’s range — whichever side, that is the direction.' },
    trap: { vi: 'Hay xuất hiện quanh tin lớn; biên độ rộng không có nghĩa là có hướng.', en: 'Common around big news; a wide range does not mean a direction.' },
    lesson: 'candles-more', patternId: 'doji',
  },

  /* ---------------- cụm nến ---------------- */
  {
    id: 'bull-harami', group: 'candle', figure: 'bull-harami', side: 'bull',
    name: { vi: 'Mẹ bồng con tăng (Harami)', en: 'Bullish harami' },
    gist: { vi: 'Sau đợt giảm: nến xanh nhỏ nằm gọn trong THÂN nến đỏ lớn trước đó. Đà giảm chững lại.', en: 'After a decline: a small green candle inside the prior large red BODY. The decline pauses.' },
    confirm: { vi: 'Nến thứ ba xanh, đóng vượt đỉnh nến đầu — thành "ba nến bên trong tăng".', en: 'A third green candle closing above the first — it becomes "three inside up".' },
    trap: { vi: 'Yếu hơn nhấn chìm: nó nói "dừng lại", chưa nói "đổi chiều".', en: 'Weaker than engulfing: it says "stopped", not yet "turned".' },
    lesson: 'candle-clusters',
  },
  {
    id: 'bear-harami', group: 'candle', figure: 'bear-harami', side: 'bear',
    name: { vi: 'Mẹ bồng con giảm', en: 'Bearish harami' },
    gist: { vi: 'Sau đợt tăng: nến đỏ nhỏ nằm gọn trong thân nến xanh lớn trước đó. Đà tăng chững lại.', en: 'After a rise: a small red candle inside the prior large green body. The rally pauses.' },
    confirm: { vi: 'Nến thứ ba đỏ, đóng dưới đáy nến đầu — thành "ba nến bên trong giảm".', en: 'A third red candle closing below the first — it becomes "three inside down".' },
    trap: { vi: 'Một harami trong xu hướng tăng mạnh thường chỉ là một nhịp nghỉ.', en: 'A harami in a strong uptrend is usually just a breather.' },
    lesson: 'candle-clusters',
  },
  {
    id: 'piercing', group: 'candle', figure: 'piercing', side: 'bull',
    name: { vi: 'Đường nhọn (Piercing line)', en: 'Piercing line' },
    gist: { vi: 'Sau nến đỏ, nến xanh mở thấp hơn nhưng đóng QUA điểm giữa thân nến đỏ.', en: 'After a red candle, a green one opens lower but closes PAST the red body’s midpoint.' },
    confirm: { vi: 'Đóng qua điểm giữa là tối thiểu; nến sau đóng cao hơn nữa thì chắc hơn.', en: 'Past the midpoint is the minimum; a higher close the next day makes it firmer.' },
    trap: { vi: 'Chưa tới điểm giữa thì chưa có tín hiệu; vượt hết thân thì đã là nhấn chìm.', en: 'Short of the midpoint there is no signal; clearing the whole body is already an engulfing.' },
    lesson: 'candle-clusters',
  },
  {
    id: 'dark-cloud', group: 'candle', figure: 'dark-cloud', side: 'bear',
    name: { vi: 'Mây đen che phủ', en: 'Dark cloud cover' },
    gist: { vi: 'Sau nến xanh, nến đỏ mở cao hơn nhưng đóng DƯỚI điểm giữa thân nến xanh.', en: 'After a green candle, a red one opens higher but closes BELOW the green body’s midpoint.' },
    confirm: { vi: 'Đóng dưới điểm giữa là tối thiểu; nến sau đóng thấp hơn nữa thì chắc hơn.', en: 'Below the midpoint is the minimum; a lower close the next day makes it firmer.' },
    trap: { vi: 'Ảnh gương của đường nhọn, cùng luật điểm giữa.', en: 'The mirror of the piercing line, same midpoint rule.' },
    lesson: 'candle-clusters',
  },
  {
    id: 'tweezer-top', group: 'candle', figure: 'tweezer-top', side: 'bear',
    name: { vi: 'Đỉnh nhíp', en: 'Tweezer top' },
    gist: { vi: 'Hai nến liên tiếp có đỉnh gần bằng nhau, nến sau đỏ: bị từ chối hai lần ở một mức.', en: 'Two consecutive candles with nearly equal highs, the second red: rejected twice at one price.' },
    confirm: { vi: 'Mạnh nhất khi trùng một vùng kháng cự có sẵn; nến sau đóng thấp hơn.', en: 'Strongest where it meets an existing resistance zone; the next candle closes lower.' },
    trap: { vi: 'Hai đỉnh bằng nhau giữa một xu hướng tăng mạnh hay chỉ là trùng hợp.', en: 'Equal highs in the middle of a strong uptrend are often coincidence.' },
    lesson: 'candle-clusters',
  },
  {
    id: 'tweezer-bottom', group: 'candle', figure: 'tweezer-bottom', side: 'bull',
    name: { vi: 'Đáy nhíp', en: 'Tweezer bottom' },
    gist: { vi: 'Hai nến liên tiếp có đáy gần bằng nhau, nến sau xanh: một mức được giữ hai lần.', en: 'Two consecutive candles with nearly equal lows, the second green: one price held twice.' },
    confirm: { vi: 'Mạnh nhất khi trùng một vùng hỗ trợ có sẵn; nến sau đóng cao hơn.', en: 'Strongest where it meets an existing support zone; the next candle closes higher.' },
    trap: { vi: 'Hai phiên không phải "hai lần chạm" theo nghĩa của vùng hỗ trợ — vùng cần các đáy xoay.', en: 'Two sessions are not "two touches" in the support-zone sense — a zone needs pivot lows.' },
    lesson: 'candle-clusters',
  },
  {
    id: 'three-soldiers', group: 'candle', figure: 'three-soldiers', side: 'bull',
    name: { vi: 'Ba chàng lính trắng', en: 'Three white soldiers' },
    gist: { vi: 'Ba nến xanh thân dài liên tiếp, mỗi nến đóng cao hơn và mở trong thân nến trước.', en: 'Three long green bodies in a row, each closing higher and opening within the prior body.' },
    confirm: { vi: 'Sau một đợt giảm hoặc đi ngang là tín hiệu lực mua bền bỉ.', en: 'After a decline or a range, a sign of sustained buying.' },
    trap: { vi: 'Sau một đợt tăng đã rất dài thì hay là cạn sức — vị trí quan trọng hơn hình dạng.', en: 'After an already long rise it is often exhaustion — location beats shape.' },
    lesson: 'candle-clusters',
  },
  {
    id: 'three-crows', group: 'candle', figure: 'three-crows', side: 'bear',
    name: { vi: 'Ba con quạ đen', en: 'Three black crows' },
    gist: { vi: 'Ba nến đỏ thân dài liên tiếp, mỗi nến đóng thấp hơn. Lực bán bền bỉ.', en: 'Three long red bodies in a row, each closing lower. Sustained selling.' },
    confirm: { vi: 'Sau một đợt tăng hoặc đi ngang là tín hiệu đảo chiều giảm.', en: 'After a rise or a range, a bearish reversal sign.' },
    trap: { vi: 'Sau một đợt giảm đã rất dài, giá thường đã gần mức hồi kỹ thuật.', en: 'After an already long decline, price is often near a technical bounce.' },
    lesson: 'candle-clusters',
  },
  {
    id: 'three-inside-up', group: 'candle', figure: 'three-inside-up', side: 'bull',
    name: { vi: 'Ba nến bên trong tăng', en: 'Three inside up' },
    gist: { vi: 'Harami tăng được xác nhận: nến thứ ba xanh, đóng vượt đỉnh nến đầu.', en: 'A confirmed bullish harami: a third green candle closes above the first.' },
    confirm: { vi: 'Chính nến thứ ba là xác nhận — chờ nó đóng cửa.', en: 'The third candle is the confirmation — wait for its close.' },
    trap: { vi: 'Đáng tin hơn harami đơn, nhưng vẫn cần vị trí: ở hỗ trợ thì có nghĩa, giữa vùng thì ít.', en: 'More reliable than a lone harami, but still needs location: meaningful at support, less so mid-range.' },
    lesson: 'candle-clusters',
  },
  {
    id: 'three-inside-down', group: 'candle', figure: 'three-inside-down', side: 'bear',
    name: { vi: 'Ba nến bên trong giảm', en: 'Three inside down' },
    gist: { vi: 'Harami giảm được xác nhận: nến thứ ba đỏ, đóng dưới đáy nến đầu.', en: 'A confirmed bearish harami: a third red candle closes below the first.' },
    confirm: { vi: 'Nến thứ ba đóng cửa là xác nhận.', en: 'The third candle’s close is the confirmation.' },
    trap: { vi: 'Ở giữa một xu hướng giảm sẵn có thì nó chỉ là xu hướng đang tiếp diễn.', en: 'Inside an existing downtrend it is just the trend continuing.' },
    lesson: 'candle-clusters',
  },
  {
    id: 'abandoned-baby', group: 'candle', figure: 'abandoned-baby', side: 'bull',
    name: { vi: 'Em bé bị bỏ rơi', en: 'Abandoned baby' },
    gist: { vi: 'Như sao mai, nhưng nến giữa là doji tách hẳn khỏi hai nến bên bằng khoảng trống giá.', en: 'Like a morning star, but the middle candle is a doji gapped away from both neighbours.' },
    confirm: { vi: 'Nến thứ ba gap lên và đóng sâu vào thân nến đầu.', en: 'The third candle gaps up and closes deep into the first body.' },
    trap: { vi: 'Hiếm gặp thật; đừng gọi tên khi hai khoảng trống chưa thật sự tách rời.', en: 'Genuinely rare; do not name it unless both gaps are real.' },
    lesson: 'candle-clusters',
  },
  {
    id: 'rising-three', group: 'continuation', figure: 'rising-three', side: 'bull',
    name: { vi: 'Tăng ba bước', en: 'Rising three methods' },
    gist: { vi: 'Nến xanh dài, ba nến nhỏ điều chỉnh nằm trong phạm vi nến đầu, rồi nến xanh dài vượt đỉnh.', en: 'A long green candle, three small pullback candles inside its range, then a long green to a new high.' },
    confirm: { vi: 'Nến thứ năm đóng trên đỉnh nến đầu.', en: 'The fifth candle closes above the first candle’s high.' },
    trap: { vi: 'Ba nến đỏ ở giữa là NGHỈ, không phải đảo chiều — chúng nằm trong nến đầu.', en: 'The red candles in the middle are a REST, not a reversal — they sit inside the first candle.' },
    lesson: 'candle-clusters',
  },
  {
    id: 'falling-three', group: 'continuation', figure: 'falling-three', side: 'bear',
    name: { vi: 'Giảm ba bước', en: 'Falling three methods' },
    gist: { vi: 'Nến đỏ dài, ba nến nhỏ hồi lên trong phạm vi nến đầu, rồi nến đỏ dài phá đáy.', en: 'A long red candle, three small bounce candles inside its range, then a long red to a new low.' },
    confirm: { vi: 'Nến thứ năm đóng dưới đáy nến đầu.', en: 'The fifth candle closes below the first candle’s low.' },
    trap: { vi: 'Ba nến xanh ở giữa là hồi kỹ thuật trong xu hướng giảm, không phải đáy.', en: 'The green candles in the middle are a bounce inside a downtrend, not a bottom.' },
    lesson: 'candle-clusters',
  },

  /* ---------------- mẫu giá ---------------- */
  {
    id: 'triple-top', group: 'reversal', figure: 'triple-top', side: 'bear',
    name: { vi: 'Ba đỉnh', en: 'Triple top' },
    gist: { vi: 'Giá ba lần thất bại ở cùng một vùng kháng cự.', en: 'Price fails three times at the same resistance zone.' },
    confirm: { vi: 'Đóng cửa dưới đáy của cả vùng dao động.', en: 'A close below the lows of the whole range.' },
    trap: { vi: 'Chưa thủng đáy thì đó chỉ là một hình chữ nhật đi ngang.', en: 'Until the lows break it is just a sideways rectangle.' },
    lesson: 'patterns-more',
  },
  {
    id: 'triple-bottom', group: 'reversal', figure: 'triple-bottom', side: 'bull',
    name: { vi: 'Ba đáy', en: 'Triple bottom' },
    gist: { vi: 'Giá ba lần giữ được cùng một vùng hỗ trợ.', en: 'Price holds the same support zone three times.' },
    confirm: { vi: 'Đóng cửa trên đỉnh của cả vùng dao động.', en: 'A close above the highs of the whole range.' },
    trap: { vi: 'Mỗi lần chạm thêm làm vùng hỗ trợ "mòn" đi; lần thứ tư hay thủng.', en: 'Each extra touch wears the support down; the fourth often breaks.' },
    lesson: 'patterns-more',
  },
  {
    id: 'rising-wedge', group: 'reversal', figure: 'rising-wedge', side: 'bear',
    name: { vi: 'Nêm tăng', en: 'Rising wedge' },
    gist: { vi: 'Giá đi lên giữa hai đường cùng dốc lên và hội tụ; đỉnh mới yếu dần.', en: 'Price rises between two up-sloping, converging lines; each new high is weaker.' },
    confirm: { vi: 'Đóng cửa dưới biên dưới của nêm.', en: 'A close below the wedge’s lower edge.' },
    trap: { vi: 'Đang tăng nhưng là hình hay gãy XUỐNG nhất — đừng mua vì "đang lên".', en: 'Rising, yet the shape most prone to breaking DOWN — do not buy because "it is going up".' },
    lesson: 'patterns-more',
  },
  {
    id: 'falling-wedge', group: 'reversal', figure: 'falling-wedge', side: 'bull',
    name: { vi: 'Nêm giảm', en: 'Falling wedge' },
    gist: { vi: 'Giá đi xuống giữa hai đường cùng dốc xuống và hội tụ; lực bán yếu dần.', en: 'Price falls between two down-sloping, converging lines; the selling weakens.' },
    confirm: { vi: 'Đóng cửa trên biên trên của nêm.', en: 'A close above the wedge’s upper edge.' },
    trap: { vi: 'Hai cạnh song song thì đó là kênh giảm, không phải nêm.', en: 'Parallel edges make a falling channel, not a wedge.' },
    lesson: 'patterns-more',
  },
  {
    id: 'rounding-bottom', group: 'reversal', figure: 'rounding-bottom', side: 'bull',
    name: { vi: 'Đáy tròn', en: 'Rounding bottom' },
    gist: { vi: 'Giảm chậm dần, đi ngang, rồi tăng chậm dần thành hình cái đĩa — chuyển đổi dài hạn.', en: 'A slowing fall, a flat stretch, then a slow rise into a saucer — a long-term turn.' },
    confirm: { vi: 'Đóng cửa trên miệng đĩa (mức bắt đầu giảm).', en: 'A close above the rim (where the decline began).' },
    trap: { vi: 'Trên nến ngày nó cần hàng tháng; vài tuần thường chỉ là một cú hồi.', en: 'On daily candles it takes months; a few weeks is usually just a bounce.' },
    lesson: 'patterns-more',
  },
  {
    id: 'cup-handle', group: 'continuation', figure: 'cup-handle', side: 'bull',
    name: { vi: 'Cốc và tay cầm', en: 'Cup and handle' },
    gist: { vi: 'Đáy tròn hình cái cốc, rồi một nhịp lùi nhỏ (tay cầm) ở nửa trên của cốc.', en: 'A rounded cup, then a small dip (the handle) in the cup’s upper half.' },
    confirm: { vi: 'Đóng cửa vượt miệng cốc, tốt nhất kèm khối lượng lớn.', en: 'A close above the rim, ideally on heavy volume.' },
    trap: { vi: 'Tay cầm lùi sâu quá nửa cốc thì mẫu hỏng.', en: 'A handle that drops below the cup’s midpoint breaks the pattern.' },
    lesson: 'patterns-more',
  },
  {
    id: 'pennant', group: 'continuation', figure: 'pennant', side: 'bull',
    name: { vi: 'Cờ đuôi nheo', en: 'Pennant' },
    gist: { vi: 'Sau một cú chạy dốc, giá co lại thành một tam giác nhỏ rồi đi tiếp hướng cũ.', en: 'After a steep run, price coils into a small triangle, then continues the old way.' },
    confirm: { vi: 'Đóng cửa ra khỏi tam giác theo hướng của cột cờ.', en: 'A close out of the triangle in the pole’s direction.' },
    trap: { vi: 'Có cả bản giảm; và co lại quá lâu thì đà đã tắt.', en: 'There is a bearish version too; and a coil that drags on has lost its momentum.' },
    lesson: 'patterns-more',
  },
  {
    id: 'rectangle', group: 'continuation', figure: 'rectangle', side: 'neutral',
    name: { vi: 'Hình chữ nhật (tích luỹ)', en: 'Rectangle (range)' },
    gist: { vi: 'Giá đi ngang giữa hỗ trợ và kháng cự song song.', en: 'Price moves sideways between parallel support and resistance.' },
    confirm: { vi: 'Đóng cửa qua một trong hai biên — biên đó quyết định hướng.', en: 'A close beyond either edge — that edge sets the direction.' },
    trap: { vi: 'Đoán hướng trước khi phá là đoán; phá giả ở biên rất thường gặp.', en: 'Calling the direction before the break is a guess; false breaks at the edges are common.' },
    lesson: 'patterns-more',
  },
  {
    id: 'channel', group: 'continuation', figure: 'channel', side: 'bull',
    name: { vi: 'Kênh giá tăng', en: 'Ascending channel' },
    gist: { vi: 'Giá dao động giữa hai đường song song cùng dốc lên.', en: 'Price oscillates between two parallel, rising lines.' },
    confirm: { vi: 'Bật lên từ biên dưới giữ cho kênh còn hiệu lực.', en: 'A bounce off the lower edge keeps the channel valid.' },
    trap: { vi: 'Thủng biên dưới là cảnh báo đầu tiên xu hướng đã đổi.', en: 'Losing the lower edge is the first warning the trend has changed.' },
    lesson: 'patterns-more',
  },

  /* ---------------- mức động ---------------- */
  {
    id: 'trendline', group: 'level', figure: 'trendline', side: 'bull',
    name: { vi: 'Đường xu hướng tăng', en: 'Uptrend line' },
    gist: { vi: 'Nối các đáy cao dần; đóng vai hỗ trợ động. Lần chạm thứ ba làm nó đáng tin.', en: 'Joins the rising lows; acts as dynamic support. The third touch makes it credible.' },
    confirm: { vi: 'Giá chạm đường và bật lên, cấu trúc đáy vẫn cao dần.', en: 'Price touches the line and bounces, with lows still rising.' },
    trap: { vi: 'Thủng đường là yếu đi; xu hướng chỉ thật sự gãy khi có một đáy thấp hơn.', en: 'A break means weakening; the trend only truly breaks on a lower low.' },
    lesson: 'trend',
  },
  {
    id: 'sr-flip', group: 'level', figure: 'sr-flip', side: 'bull',
    name: { vi: 'Đổi vai: kháng cự → hỗ trợ', en: 'Role reversal: resistance → support' },
    gist: { vi: 'Kháng cự bị phá lên thường thành hỗ trợ mới; giá hay quay lại kiểm tra nó.', en: 'Broken resistance often becomes new support; price frequently retests it.' },
    confirm: { vi: 'Giá quay về vùng cũ từ phía trên và đóng cửa vẫn trên vùng.', en: 'Price returns to the old zone from above and still closes above it.' },
    trap: { vi: 'Đóng cửa lại xuống dưới vùng khi kiểm tra = phá vỡ giả.', en: 'Closing back below the zone on the retest = a false breakout.' },
    lesson: 'trend',
  },

  /* ---------------- chỉ báo ---------------- */
  {
    id: 'ma-cross', group: 'indicator', figure: 'ma-cross', side: 'neutral',
    name: { vi: 'Giao cắt vàng / tử thần', en: 'Golden / death cross' },
    gist: { vi: 'MA ngắn cắt lên MA dài là giao cắt vàng; cắt xuống là giao cắt tử thần. Cặp cổ điển: SMA50 và SMA200.', en: 'A short MA crossing above a long one is a golden cross; below, a death cross. The classic pair: SMA50 and SMA200.' },
    confirm: { vi: 'Giá giữ được phía trên (dưới) cả hai đường sau khi cắt.', en: 'Price holds above (below) both lines after the cross.' },
    trap: { vi: 'Đến SAU cú chạy, và cắt qua cắt lại liên tục khi thị trường đi ngang.', en: 'Arrives AFTER the move, and whipsaws when the market ranges.' },
    lesson: 'indicators',
  },
  {
    id: 'rsi', group: 'indicator', figure: 'rsi', side: 'neutral',
    name: { vi: 'RSI (14)', en: 'RSI (14)' },
    gist: { vi: 'Sức của phiên tăng so với phiên giảm, thang 0–100. Trên 70 quá mua, dưới 30 quá bán.', en: 'Up-session strength against down-session strength, 0–100. Above 70 overbought, below 30 oversold.' },
    confirm: { vi: 'Phân kỳ: giá tạo đỉnh (đáy) mới mà RSI không theo.', en: 'Divergence: price makes a new high (low) and RSI does not.' },
    trap: { vi: 'Trong xu hướng mạnh RSI có thể ở trên 70 hàng tuần — quá mua không phải lệnh bán.', en: 'In a strong trend RSI can sit above 70 for weeks — overbought is not a sell order.' },
    lesson: 'indicators',
  },
  {
    id: 'macd', group: 'indicator', figure: 'macd', side: 'neutral',
    name: { vi: 'MACD (12, 26, 9)', en: 'MACD (12, 26, 9)' },
    gist: { vi: 'EMA12 − EMA26, so với đường tín hiệu EMA9 của chính nó. Histogram là hiệu hai đường.', en: 'EMA12 − EMA26, against its own EMA9 signal line. The histogram is their difference.' },
    confirm: { vi: 'MACD cắt lên đường tín hiệu = động lượng tăng; cắt xuống = giảm.', en: 'MACD crossing above the signal = rising momentum; below = falling.' },
    trap: { vi: 'Là chỉ báo động lượng tính từ trung bình — còn trễ hơn cả MA.', en: 'A momentum gauge built from averages — it lags even more than an MA.' },
    lesson: 'indicators',
  },
  {
    id: 'bollinger', group: 'indicator', figure: 'bollinger', side: 'neutral',
    name: { vi: 'Dải Bollinger (20, 2)', en: 'Bollinger Bands (20, 2)' },
    gist: { vi: 'SMA20 cộng trừ 2 độ lệch chuẩn — thước đo biến động. Dải bó hẹp thường báo trước một đợt chạy mạnh.', en: 'SMA20 plus and minus 2 standard deviations — a volatility gauge. A squeeze often precedes a big move.' },
    confirm: { vi: 'Sau khi bó hẹp, giá đóng cửa ra ngoài dải kèm khối lượng.', en: 'After a squeeze, a close outside a band on volume.' },
    trap: { vi: 'Chạm dải ngoài tự nó không phải tín hiệu mua hay bán.', en: 'Touching an outer band is not a buy or sell signal by itself.' },
    lesson: 'indicators',
  },
  {
    id: 'volume-confirm', group: 'indicator', figure: 'volume-confirm', side: 'neutral',
    name: { vi: 'Khối lượng xác nhận', en: 'Volume confirmation' },
    gist: { vi: 'Phá vỡ kèm khối lượng lớn đáng tin hơn; giá tăng mà khối lượng cạn dần là đà đang yếu.', en: 'A breakout on heavy volume is more credible; price rising on fading volume is a tiring rally.' },
    confirm: { vi: 'Khối lượng nến phá ≥ 1,5–2× trung bình 20 phiên.', en: 'Breakout-candle volume ≥ 1.5–2× the 20-session average.' },
    trap: { vi: 'Khối lượng cao ngày đáo hạn quyền chọn hay ngày cơ cấu chỉ số không nói gì về hướng.', en: 'High volume on option expiry or index rebalance days says nothing about direction.' },
    lesson: 'indicators',
  },
];
